Repository entur/terraform-google-sql-db, pull requests merged in 2022-07, with the labels that each got.

#9 chore: Add auto-bump of release version in README.md and main example
  README.md
  examples/minimal/main.tf
Labels: documentation

#6 fix: force tcp for proxy
  modules/postgresql/main.tf
Labels: bug, enhancement

#5 fix: add database_name override
  examples/minimal/main.tf
  examples/minimal_test/main.tf
  modules/postgresql/README.md
  modules/postgresql/main.tf
  modules/postgresql/outputs.tf
  modules/postgresql/variables.tf
Labels: enhancement
